# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyApplication.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import resources_qrc
from PyQt5.QtWidgets import QWidget, QFileDialog, QLabel, QVBoxLayout, QPushButton, QWidget
from PyQt5.QtGui import QPixmap

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, central_widget_parent):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1384, 824)
        MainWindow.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.centralwidget = QWidget(central_widget_parent)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.icon_name_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_name_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.icon_name_widget.setMaximumSize(QtCore.QSize(175, 2000))
        self.icon_name_widget.setStyleSheet("QWidget{\n"
                                            "background-color: rgb(31, 149, 239);\n"
                                            "    border-top-left-radius:10px;\n"
                                            "    border-bottom-left-radius:10px;\n"
                                            "color: white;\n"
                                            "icon_name_page.setVisible(True)\n"
                                            "\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "QPushButton{\n"
                                            "    color: white;\n"
                                            "     text-align:left;\n"
                                            "    height:30px;\n"
                                            "    border:none;\n"
                                            "    padding-left:10px;\n"
                                            "    border-top-left-radius:10px;\n"
                                            "    border-bottom-left-radius:10px;\n"
                                            "}\n"
                                            "QPushButton:checked{\n"
                                            "    background-color: #F5FAFE;\n"
                                            "    color: #1F95FE;\n"
                                            "    font-weight: bold;\n"
                                            "\n"
                                            "}\n"
                                            "")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.icon_name_widget)
        self.label_4.setMinimumSize(QtCore.QSize(60, 60))
        self.label_4.setStyleSheet("QLabel {\n"
                                   "    border-image: url(:/Images/profilephoto.jpg);\n"
                                   "   \n"
                                   "    border-radius: 30px;    \n"
                                   "}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.icon_name_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
                                   "margin-right:5px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.icon_name_widget)
        self.line_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.line_2.setStyleSheet("    margin-right:10px;\n"
                                  "margin-left:10px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dashboard_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.dashboard_2.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/dashboard_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/Images/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dashboard_2.setIcon(icon)
        self.dashboard_2.setCheckable(True)
        self.dashboard_2.setAutoExclusive(True)
        self.dashboard_2.setObjectName("dashboard_2")
        self.verticalLayout_2.addWidget(self.dashboard_2)
        self.profile_2 = QtWidgets.QPushButton(self.icon_name_widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/profile_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/Images/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.profile_2.setIcon(icon1)
        self.profile_2.setCheckable(True)
        self.profile_2.setAutoExclusive(True)
        self.profile_2.setObjectName("profile_2")
        self.verticalLayout_2.addWidget(self.profile_2)
        self.project_img_name_1 = QtWidgets.QPushButton(self.icon_name_widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/Images/icons8-graduate-student-studying-about-her-professional-studies-96.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/Images/a.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.project_img_name_1.setIcon(icon2)
        self.project_img_name_1.setCheckable(True)
        self.project_img_name_1.setAutoExclusive(True)
        self.project_img_name_1.setObjectName("project_img_name_1")
        self.verticalLayout_2.addWidget(self.project_img_name_1)
        self.project_img_name_2 = QtWidgets.QPushButton(self.icon_name_widget)
        self.project_img_name_2.setIcon(icon2)
        self.project_img_name_2.setCheckable(True)
        self.project_img_name_2.setAutoExclusive(True)
        self.project_img_name_2.setObjectName("project_img_name_2")
        self.verticalLayout_2.addWidget(self.project_img_name_2)
        self.project_img_name_3 = QtWidgets.QPushButton(self.icon_name_widget)
        self.project_img_name_3.setIcon(icon2)
        self.project_img_name_3.setCheckable(True)
        self.project_img_name_3.setAutoExclusive(True)
        self.project_img_name_3.setObjectName("project_img_name_3")
        self.verticalLayout_2.addWidget(self.project_img_name_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 342, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.line_4 = QtWidgets.QFrame(self.icon_name_widget)
        self.line_4.setStyleSheet("    margin-right:10px;\n"
                                  "margin-left:10px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        self.signout_2 = QtWidgets.QPushButton(self.icon_name_widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/log_out_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/Images/log_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.signout_2.setIcon(icon3)
        self.signout_2.setIconSize(QtCore.QSize(16, 16))
        self.signout_2.setCheckable(True)
        self.signout_2.setAutoExclusive(False)
        self.signout_2.setObjectName("signout_2")
        self.verticalLayout_4.addWidget(self.signout_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.header_widget = QtWidgets.QWidget(self.main_widget)
        self.header_widget.setObjectName("header_widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.header_widget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.header_widget)
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_8.addWidget(self.pushButton_10, 0, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.header_widget)
        self.pushButton_11.setStyleSheet("border:none;")
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Images/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_8.addWidget(self.pushButton_11, 0, 5, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.header_widget)
        self.pushButton_9.setStyleSheet("border:none;")
        self.pushButton_9.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Images/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setAutoExclusive(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_8.addWidget(self.pushButton_9, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.header_widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_8.addWidget(self.lineEdit, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(206, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(206, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 4, 1, 1)
        self.gridLayout_7.addWidget(self.header_widget, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(750, 0))
        self.stackedWidget.setStyleSheet("\n"
                                         "background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard_page_1 = QtWidgets.QWidget()
        self.dashboard_page_1.setObjectName("dashboard_page_1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.dashboard_page_1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.dashboard_label_1 = QtWidgets.QLabel(self.dashboard_page_1)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.dashboard_label_1.setFont(font)
        self.dashboard_label_1.setObjectName("dashboard_label_1")
        self.gridLayout_11.addWidget(self.dashboard_label_1, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.dashboard_page_1)

        self.project_page_2 = QtWidgets.QWidget()
        self.project_page_2.setObjectName("project_page_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.project_page_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_57 = QtWidgets.QLabel(self.project_page_2)
        self.label_57.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(15)
        font.setBold(True)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_12.addWidget(self.label_57, 0, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_52.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_52.addItem(spacerItem5)
        self.label_58 = QtWidgets.QLabel(self.project_page_2)
        self.label_58.setMinimumSize(QtCore.QSize(400, 400))
        self.label_58.setMaximumSize(QtCore.QSize(400, 400))
        self.label_58.setStyleSheet("border: 2px solid rgb(51, 169, 239);"
                                    "border-radius: 10px;"
                                    )
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.verticalLayout_52.addWidget(self.label_58)
        self.label_59 = QtWidgets.QLabel(self.project_page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_52.addWidget(self.label_59)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_52.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_52.addItem(spacerItem7)
        self.horizontalLayout_16.addLayout(self.verticalLayout_52)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem13)
        self.pushButton_4 = QtWidgets.QPushButton(self.project_page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(31, 149, 239);\n"
                                        "    color: white;\n"
                                        "    border: 2px solid rgb(31, 149, 239);\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px 10px;\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(20, 122, 200);\n"
                                        "    border-color: rgb(20, 122, 200);\n"
                                        "}\n"
                                        "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Images/icons8-photo-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_53.addWidget(self.pushButton_4)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem15)
        self.label_2 = QtWidgets.QLabel(self.project_page_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_53.addWidget(self.label_2)
        self.comboBox_9 = QtWidgets.QComboBox(self.project_page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_9.sizePolicy().hasHeightForWidth())
        self.comboBox_9.setSizePolicy(sizePolicy)
        self.comboBox_9.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_9.setStyleSheet("\n"
                                      "            QComboBox {\n"
                                      "                border: 1px solid rgb(31, 149, 239);\n"
                                      "                border-radius: 5px;\n"
                                      "                padding: 3px;\n"
                                      "                background-color: white;\n"
                                      "                selection-background-color: rgb(31, 149, 239);\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox::drop-down {\n"
                                      "                subcontrol-origin: padding;\n"
                                      "                subcontrol-position: top right;\n"
                                      "                width: 20px;\n"
                                      "                border-left: 1px solid rgb(31, 149, 239);\n"
                                      "            }\n"
                                      "\n"
                                      "         QComboBox::down-arrow {\n"
                                      "    image: url(:/Images/icons8-sort-down-30.png);\n"
                                      "    width: 12px;\n"
                                      "    height: 12px;\n"
                                      "}\n"
                                      "\n"
                                      "\n"
                                      "            QComboBox:hover {\n"
                                      "                border-color: rgb(51, 169, 239);\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox::hover {\n"
                                      "                background-color: rgb(235, 245, 255);\n"
                                      "            }")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_53.addWidget(self.comboBox_9)

        self.pushButton_6 = QtWidgets.QPushButton(self.project_page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(31, 149, 239);\n"
                                        "    color: white;\n"
                                        "    border: 2px solid rgb(31, 149, 239);\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px 10px;\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(20, 122, 200);\n"
                                        "    border-color: rgb(20, 122, 200);\n"
                                        "}\n"
                                        "")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_53.addWidget(self.pushButton_6)


        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem16)
        self.label_12 = QtWidgets.QLabel(self.project_page_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_53.addWidget(self.label_12)
        self.comboBox_10 = QtWidgets.QComboBox(self.project_page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_10.sizePolicy().hasHeightForWidth())
        self.comboBox_10.setSizePolicy(sizePolicy)
        self.comboBox_10.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_10.setStyleSheet("\n"
                                       "            QComboBox {\n"
                                       "                border: 1px solid rgb(31, 149, 239);\n"
                                       "                border-radius: 5px;\n"
                                       "                padding: 3px;\n"
                                       "                background-color: white;\n"
                                       "                selection-background-color: rgb(31, 149, 239);\n"
                                       "            }\n"
                                       "\n"
                                       "            QComboBox::drop-down {\n"
                                       "                subcontrol-origin: padding;\n"
                                       "                subcontrol-position: top right;\n"
                                       "                width: 20px;\n"
                                       "                border-left: 1px solid rgb(31, 149, 239);\n"
                                       "            }\n"
                                       "\n"
                                       "         QComboBox::down-arrow {\n"
                                       "    image: url(:/Images/icons8-sort-down-30.png);\n"
                                       "    width: 12px;\n"
                                       "    height: 12px;\n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "            QComboBox:hover {\n"
                                       "                border-color: rgb(51, 169, 239);\n"
                                       "            }\n"
                                       "\n"
                                       "            QComboBox::hover {\n"
                                       "                background-color: rgb(235, 245, 255);\n"
                                       "            }")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.verticalLayout_53.addWidget(self.comboBox_10)
        self.pushButton = QtWidgets.QPushButton(self.project_page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    background-color: rgb(31, 149, 239);\n"
                                      "    color: white;\n"
                                      "    border: 2px solid rgb(31, 149, 239);\n"
                                      "    border-radius: 5px;\n"
                                      "    padding: 5px 10px;\n"
                                      "\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: rgb(20, 122, 200);\n"
                                      "    border-color: rgb(20, 122, 200);\n"
                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_53.addWidget(self.pushButton)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem18)
        self.pushButton_2 = QtWidgets.QPushButton(self.project_page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(31, 149, 239);\n"
                                        "    color: white;\n"
                                        "    border: 2px solid rgb(31, 149, 239);\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px 10px;\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(20, 122, 200);\n"
                                        "    border-color: rgb(20, 122, 200);\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_53.addWidget(self.pushButton_2)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem19)
        self.pushButton_5 = QtWidgets.QPushButton(self.project_page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(31, 149, 239);\n"
                                        "    color: white;\n"
                                        "    border: 2px solid rgb(31, 149, 239);\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px 10px;\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(20, 122, 200);\n"
                                        "    border-color: rgb(20, 122, 200);\n"
                                        "}\n"
                                        "")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_53.addWidget(self.pushButton_5)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem20)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem22)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem23)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem24)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem25)
        self.horizontalLayout_16.addLayout(self.verticalLayout_53)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem26)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_54.addItem(spacerItem27)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_54.addItem(spacerItem28)
        self.label_60 = QtWidgets.QLabel(self.project_page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_60.setMinimumSize(QtCore.QSize(400, 400))
        self.label_60.setMaximumSize(QtCore.QSize(400, 400))
        self.label_60.setStyleSheet("border: 2px solid rgb(51, 169, 239);"
                                    "border-radius: 10px;"
                                    )
        self.label_60.setText("")
        self.label_60.setObjectName("label_60")
        self.verticalLayout_54.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(self.project_page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_54.addWidget(self.label_61)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_54.addItem(spacerItem29)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_54.addItem(spacerItem30)
        self.horizontalLayout_16.addLayout(self.verticalLayout_54)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem31)
        self.gridLayout_12.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.project_page_2)



        self.project_page_1 = QtWidgets.QWidget()
        self.project_page_1.setObjectName("project_page_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.project_page_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_52 = QtWidgets.QLabel(self.project_page_1)
        self.label_52.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(15)
        font.setBold(True)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_47.addWidget(self.label_52)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem4)
        self.label_53 = QtWidgets.QLabel(self.project_page_1)
        self.label_53.setMinimumSize(QtCore.QSize(400, 400))
        self.label_53.setMaximumSize(QtCore.QSize(400, 400))
        self.label_53.setStyleSheet("border: 2px solid rgb(51, 169, 239);"
                                    "border-radius: 10px;"
                                    )
        self.label_53.setText("")
        self.label_53.setObjectName("label_53")
        self.verticalLayout_48.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.project_page_1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_48.addWidget(self.label_54)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_48.addItem(spacerItem5)
        self.horizontalLayout_15.addLayout(self.verticalLayout_48)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_49.addItem(spacerItem7)
        self.pushButton_3 = QtWidgets.QPushButton(self.project_page_1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
                                        "    background-color: rgb(31, 149, 239);\n"
                                        "    color: white;\n"
                                        "    border: 2px solid rgb(31, 149, 239);\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px 10px;\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(20, 122, 200);\n"
                                        "    border-color: rgb(20, 122, 200);\n"
                                        "}\n"
                                        "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Images/icons8-photo-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon7)
        self.pushButton_3.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_49.addWidget(self.pushButton_3)

        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_49.addItem(spacerItem8)
        self.pushButton_13 = QtWidgets.QPushButton(self.project_page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_13.setStyleSheet("  QPushButton {\n"
                                         "                background-color: rgb(31, 149, 239);\n"
                                         "                color: white;\n"
                                         "                border: 2px solid rgb(31, 149, 239);\n"
                                         "                border-radius: 5px;\n"
                                         "                padding: 5px 10px;\n"
                                         "            }\n"
                                         "\n"
                                         "            QPushButton:hover {\n"
                                         "                background-color: rgb(20, 122, 200);\n"
                                         "                border-color: rgb(20, 122, 200);\n"
                                         "            }")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../Desktop/My Application/Images/icons8-compress-100.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon8)
        self.pushButton_13.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_49.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.project_page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_14.setStyleSheet("  QPushButton {\n"
                                         "                background-color: rgb(31, 149, 239);\n"
                                         "                color: white;\n"
                                         "                border: 2px solid rgb(31, 149, 239);\n"
                                         "                border-radius: 5px;\n"
                                         "                padding: 5px 10px;\n"
                                         "            }\n"
                                         "\n"
                                         "            QPushButton:hover {\n"
                                         "                background-color: rgb(20, 122, 200);\n"
                                         "                border-color: rgb(20, 122, 200);\n"
                                         "            }")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../Desktop/My Application/Images/icons8-decompress-100.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon9)
        self.pushButton_14.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_49.addWidget(self.pushButton_14)
        self.comboBox_8 = QtWidgets.QComboBox(self.project_page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_8.sizePolicy().hasHeightForWidth())
        self.comboBox_8.setSizePolicy(sizePolicy)
        self.comboBox_8.setStyleSheet("\n"
                                      "            QComboBox {\n"
                                      "                border: 1px solid rgb(31, 149, 239);\n"
                                      "                border-radius: 5px;\n"
                                      "                padding: 3px;\n"
                                      "                background-color: white;\n"
                                      "                selection-background-color: rgb(31, 149, 239);\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox::drop-down {\n"
                                      "                subcontrol-origin: padding;\n"
                                      "                subcontrol-position: top right;\n"
                                      "                width: 20px;\n"
                                      "                border-left: 1px solid rgb(31, 149, 239);\n"
                                      "            }\n"
                                      "\n"
                                      "         QComboBox::down-arrow {\n"
                                      "    image: url(:/Images/icons8-sort-down-30.png);\n"
                                      "    width: 12px;\n"
                                      "    height: 12px;\n"
                                      "}\n"
                                      "\n"
                                      "\n"
                                      "            QComboBox:hover {\n"
                                      "                border-color: rgb(51, 169, 239);\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox::hover {\n"
                                      "                background-color: rgb(235, 245, 255);\n"
                                      "            }")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.verticalLayout_49.addWidget(self.comboBox_8)

        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_49.addItem(spacerItem9)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.project_page_1)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(150, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(300, 300))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
                                      "    border: 1px solid rgb(31, 149, 239);\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "\n"
                                      "QLineEdit::placeholder {\n"
                                      "    color: rgb(128, 128, 128); \n"
                                      "}\n"
                                      "\n"
                                      "")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setPlaceholderText("Enter degrees between 0-360")

        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_49.addWidget(self.lineEdit_5)
        self.pushButton_15 = QtWidgets.QPushButton(self.project_page_1)
        self.pushButton_15.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("  QPushButton {\n"
                                         "                background-color: rgb(31, 149, 239);\n"
                                         "                color: white;\n"
                                         "                border: 2px solid rgb(31, 149, 239);\n"
                                         "                border-radius: 5px;\n"
                                         "                padding: 5px 10px;\n"
                                         "            }\n"
                                         "\n"
                                         "            QPushButton:hover {\n"
                                         "                background-color: rgb(20, 122, 200);\n"
                                         "                border-color: rgb(20, 122, 200);\n"
                                         "            }")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../Desktop/My Application/Images/icons8-arrow-left-and-right-96.png"),
                         QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon10)
        self.pushButton_15.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_49.addWidget(self.pushButton_15)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_49.addItem(spacerItem10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_49)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_50.addItem(spacerItem12)
        self.label_55 = QtWidgets.QLabel(self.project_page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setMinimumSize(QtCore.QSize(400, 400))
        self.label_55.setMaximumSize(QtCore.QSize(400, 400))
        self.label_55.setStyleSheet("border: 2px solid rgb(51, 169, 239);"
                                    "border-radius: 10px;"
                                    )
        self.label_55.setText("")
        self.label_55.setObjectName("label_55")
        self.verticalLayout_50.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.project_page_1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_50.addWidget(self.label_56)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_50.addItem(spacerItem13)
        self.horizontalLayout_15.addLayout(self.verticalLayout_50)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.verticalLayout_47.addLayout(self.horizontalLayout_15)
        self.gridLayout_4.addLayout(self.verticalLayout_47, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.project_page_1)
        self.project_page_3 = QtWidgets.QWidget()
        self.project_page_3.setObjectName("project_page_3")
        self.stackedWidget.addWidget(self.project_page_3)
        self.profile_page_1 = QtWidgets.QWidget()
        self.profile_page_1.setObjectName("profile_page_1")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.profile_page_1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget = QtWidgets.QWidget(self.profile_page_1)
        self.widget.setStyleSheet("QWidget{\n"
                                  "border-radius:25px;\n"
                                  "background-color:white;\n"
                                  "color:  rgb(31, 149, 239);\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(20, 104, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setMinimumSize(QtCore.QSize(100, 100))
        self.label_9.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_9.setStyleSheet("QLabel {\n"
                                   "    border-image: url(:/Images/profilephoto.jpg);\n"
                                   "    border-radius: 50px;  \n"
                                   "\n"
                                   "    \n"
                                   "}\n"
                                   "\n"
                                   "")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem18, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setStyleSheet("background-color: rgb(31, 149, 239);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 4, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem19, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.profile_page_1)
        self.widget_2.setStyleSheet("color:  rgb(31, 149, 239)")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem20, 5, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_2, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.profile_page_1)
        self.gridLayout_7.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.main_widget, 0, 2, 1, 1)
        self.icon_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.icon_widget.setMaximumSize(QtCore.QSize(100, 2000))
        self.icon_widget.setStyleSheet("QWidget{\n"
                                       "background-color: rgb(31, 149, 239);\n"
                                       "    border-top-left-radius:10px;\n"
                                       "    border-bottom-left-radius:10px;\n"
                                       "}\n"
                                       "QPushButton{\n"
                                       "    color: white;\n"
                                       " border:none;\n"
                                       "height:30px;\n"
                                       "border-radius:10px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:checked{\n"
                                       "toggled:true;\n"
                                       "\n"
                                       "}\n"
                                       "")
        self.icon_widget.setObjectName("icon_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_widget)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem21)
        self.label_5 = QtWidgets.QLabel(self.icon_widget)
        self.label_5.setMinimumSize(QtCore.QSize(60, 60))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("QLabel {\n"
                                   "    border-image: url(:/Images/profilephoto.jpg);\n"
                                   "    border-radius: 30px;  \n"
                                   "\n"
                                   "    \n"
                                   "}\n"
                                   "\n"
                                   "")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem22)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.icon_widget)
        self.line.setStyleSheet("    margin-right:10px;\n"
                                "margin-left:10px;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboard_1 = QtWidgets.QPushButton(self.icon_widget)
        self.dashboard_1.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Images/dashboard_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/Images/dashboard_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dashboard_1.setIcon(icon11)
        self.dashboard_1.setCheckable(True)
        self.dashboard_1.setAutoExclusive(True)
        self.dashboard_1.setObjectName("dashboard_1")
        self.verticalLayout.addWidget(self.dashboard_1)
        self.profile_1 = QtWidgets.QPushButton(self.icon_widget)
        self.profile_1.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Images/profile_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":/Images/profile_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.profile_1.setIcon(icon12)
        self.profile_1.setCheckable(True)
        self.profile_1.setAutoExclusive(True)
        self.profile_1.setObjectName("profile_1")
        self.verticalLayout.addWidget(self.profile_1)
        self.project_img_1 = QtWidgets.QPushButton(self.icon_widget)
        self.project_img_1.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(
            QtGui.QPixmap(":/Images/icons8-graduate-student-studying-about-her-professional-studies-96.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(
            QtGui.QPixmap(":/Images/icons8-graduate-student-studying-about-her-professional-studies-96.png"),
            QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.project_img_1.setIcon(icon13)
        self.project_img_1.setCheckable(True)
        self.project_img_1.setAutoExclusive(True)
        self.project_img_1.setObjectName("project_img_1")
        self.verticalLayout.addWidget(self.project_img_1)
        self.project_img_2 = QtWidgets.QPushButton(self.icon_widget)
        self.project_img_2.setText("")
        self.project_img_2.setIcon(icon13)
        self.project_img_2.setCheckable(True)
        self.project_img_2.setAutoExclusive(True)
        self.project_img_2.setObjectName("project_img_2")
        self.verticalLayout.addWidget(self.project_img_2)
        self.project_img_3 = QtWidgets.QPushButton(self.icon_widget)
        self.project_img_3.setText("")
        self.project_img_3.setIcon(icon13)
        self.project_img_3.setCheckable(True)
        self.project_img_3.setAutoExclusive(True)
        self.project_img_3.setObjectName("project_img_3")
        self.verticalLayout.addWidget(self.project_img_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem23 = QtWidgets.QSpacerItem(20, 342, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem23)
        self.line_3 = QtWidgets.QFrame(self.icon_widget)
        self.line_3.setStyleSheet("    margin-right:10px;\n"
                                  "margin-left:10px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.line_5 = QtWidgets.QFrame(self.icon_widget)
        self.line_5.setStyleSheet("    margin-right:10px;\n"
                                  "margin-left:10px;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.signout_1 = QtWidgets.QPushButton(self.icon_widget)
        self.signout_1.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Images/log_out_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signout_1.setIcon(icon14)
        self.signout_1.setCheckable(True)
        self.signout_1.setObjectName("signout_1")
        self.verticalLayout_3.addWidget(self.signout_1)
        self.gridLayout.addWidget(self.icon_widget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_9.toggled['bool'].connect(self.icon_widget.setHidden)  # type: ignore
        self.pushButton_9.toggled['bool'].connect(self.icon_name_widget.setVisible)  # type: ignore
        self.project_img_3.toggled['bool'].connect(self.project_img_name_3.setChecked)  # type: ignore
        self.project_img_2.toggled['bool'].connect(self.project_img_name_2.setChecked)  # type: ignore
        self.project_img_1.toggled['bool'].connect(self.project_img_name_1.setChecked)  # type: ignore
        self.profile_1.toggled['bool'].connect(self.profile_2.setChecked)  # type: ignore
        self.project_img_name_3.toggled['bool'].connect(self.project_img_3.setChecked)  # type: ignore
        self.project_img_name_2.toggled['bool'].connect(self.project_img_2.setChecked)  # type: ignore
        self.project_img_name_1.toggled['bool'].connect(self.project_img_1.setChecked)  # type: ignore
        self.profile_2.toggled['bool'].connect(self.profile_1.setChecked)  # type: ignore
        self.signout_1.toggled['bool'].connect(self.signout_2.setChecked)  # type: ignore
        self.signout_2.toggled['bool'].connect(self.signout_1.setChecked)  # type: ignore
        self.signout_1.toggled['bool'].connect(MainWindow.close)  # type: ignore
        self.signout_2.toggled['bool'].connect(MainWindow.close)  # type: ignore
        self.dashboard_1.toggled['bool'].connect(self.dashboard_2.setChecked)  # type: ignore
        self.dashboard_2.toggled['bool'].connect(self.dashboard_1.setChecked)  # type: ignore
        self.dashboard_1.toggled['bool'].connect(self.icon_widget.setHidden)  # type: ignore
        self.dashboard_1.toggled['bool'].connect(self.icon_name_widget.setVisible)  # type: ignore
        self.project_img_3.toggled['bool'].connect(self.icon_widget.setHidden)  # type: ignore
        self.project_img_3.toggled['bool'].connect(self.icon_name_widget.setVisible)  # type: ignore
        self.project_img_2.toggled['bool'].connect(self.icon_widget.setHidden)  # type: ignore
        self.project_img_2.toggled['bool'].connect(self.icon_name_widget.setVisible)  # type: ignore
        self.project_img_1.toggled['bool'].connect(self.icon_widget.setHidden)  # type: ignore
        self.project_img_1.toggled['bool'].connect(self.icon_name_widget.setVisible)  # type: ignore
        self.profile_1.toggled['bool'].connect(self.icon_widget.setHidden)  # type: ignore
        self.profile_1.toggled['bool'].connect(self.icon_name_widget.setVisible)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_6.setText(_translate("MainWindow", "Uygula"))
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "SideBar"))
        self.dashboard_2.setText(_translate("MainWindow", "Dashboard"))
        self.profile_2.setText(_translate("MainWindow", "Profile"))
        self.project_img_name_1.setText(_translate("MainWindow", "Project 1"))
        self.project_img_name_2.setText(_translate("MainWindow", "Project 2"))
        self.project_img_name_3.setText(_translate("MainWindow", "Project 3"))
        self.signout_2.setText(_translate("MainWindow", "Sign Out"))
        self.dashboard_label_1.setText(_translate("MainWindow", "Dashboard Page"))
        self.label_57.setText(_translate("MainWindow", "Görüntü Üzerinde İşlemler - 2"))
        self.label_59.setText(_translate("MainWindow", "Orjinal Resim"))
        self.pushButton_4.setText(_translate("MainWindow", "Yükle"))
        self.label_2.setText(_translate("MainWindow", " S- Curve metodu"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Standart Sigmoid Fonksiyonu"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Yatay Kaydırılmış Sigmoid Fonksiyonu"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "Eğimli Sigmoid Fonksiyonu"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Kendi Ürettiğim Fonksiyon"))
        self.label_12.setText(_translate("MainWindow", "Hough transform metodu"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Yol Çizgileri"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Yüz Resminde Gözler"))
        self.pushButton.setText(_translate("MainWindow", "Uygula"))
        self.pushButton_2.setText(_translate("MainWindow", "Nesneleri Sayma ve Özellik Çıkarma"))
        self.pushButton_5.setText(_translate("MainWindow", "Deblurring"))
        self.label_61.setText(_translate("MainWindow", "Ölçeklendirilen Resim"))
        self.label_52.setText(_translate("MainWindow", "Görüntü Üzerinde İşlemler"))
        self.label_54.setText(_translate("MainWindow", "Orjinal Resim"))
        self.pushButton_3.setText(_translate("MainWindow", "Yükle"))
        self.pushButton_13.setText(_translate("MainWindow", "Küçült"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "1x"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "2x"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "3x"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "4x"))
        self.pushButton_14.setText(_translate("MainWindow", "Büyült"))
        self.pushButton_15.setText(_translate("MainWindow", "Döndür"))
        self.label_56.setText(_translate("MainWindow", "Ölçeklendirilen Resim"))
        self.label.setText(_translate("MainWindow", "Muzaffer Beysan Kalem"))
        self.label_6.setText(_translate("MainWindow", "Student ID: 231229095"))
        self.label_7.setText(_translate("MainWindow", "Section: Software Engineer"))
        self.label_8.setText(_translate("MainWindow", "School: Konya Teknik University"))
        self.label_10.setText(_translate("MainWindow", "E-Mail: mbk95mb95@gmail.com"))
        self.label_11.setText(_translate("MainWindow", "Phone Number: 05443584130"))
